### ISSUE TITLE
运行报错，日志错误内容如下

### ISSUE THREAD

**Issue by XNNNN** [sirodeneko/genshin-sign#16]
'NoneType' object is not subscriptable

**Comment by XNNNN** [comment]
![image](https://user-images.githubusercontent.com/29226075/155649553-00fd52b1-a5ca-4f4f-b3ee-a6cb06ddf919.png)

**Comment by bitqiu** [comment]
cookie 不对

**Comment by XNNNN** [comment]
> cookie 不对

嗯嗯重新填了一遍，应该是过期了

**Comment by XNNNN** [comment]
> cookie 不对

嗯嗯重新填了一遍，应该是过期了
