### ISSUE TITLE
cookie变化就要重新设置嘛,能自动获取最新cookie嘛

### ISSUE THREAD

**Issue by wuzesen** [sirodeneko/genshin-sign#25]
每次cookie过期都要重新设置吗?

**Comment by sirodeneko** [comment]
我cookie大半年没动过了，不太容易过期吧

**Comment by wuzesen** [comment]
登录失败,怎么查是什么原因呢
![image](https://user-images.githubusercontent.com/20244141/161386904-fbb156f2-ab64-43a8-a6be-9a109769a061.png)

**Comment by wuzesen** [comment]
本来刚开始还是可以签到的,现在一直都是尚未登录

**Comment by sirodeneko** [comment]
自测没毛病，你网页上登录了吗，
![image](https://user-images.githubusercontent.com/48661001/161412777-f887d92f-ff2f-4741-9571-a02d1c3ef76b.png)

**Comment by wuzesen** [comment]
![image](https://user-images.githubusercontent.com/20244141/161426550-d5eb9576-5c67-41b2-9b5a-63084fb59fc7.png)

我模拟了你的接口,发现返回也是尚未登录,这些参数有问题嘛

**Comment by wuzesen** [comment]
我退出重新登录获取新的cookie就可以了
