### ISSUE TITLE
国际服hoyolab自动签到报错了

### ISSUE THREAD

**Issue by SCCCyy** [sirodeneko/genshin-sign#26]
'NoneType' object has no attribute 'get'
Error: Process completed with exit code 255.

重新用无痕模式获取cookie后，依然报错

**Comment by xiaocao666tzh** [comment]
> 'NoneType' object has no attribute 'get' Error: Process completed with exit code 255.
> 
> 重新用无痕模式获取cookie后，依然报错

我昨天使用没有报错，是正常的。国际服获取长坡街变量那里与国服不一样，是OS_COOKIE看看是不是搞错了

**Comment by ixuner** [comment]
一开始我也是只用 `cookie_token` 的字段，和你一样的错误，得到的 `cookie` 那一大串要全选复制才对。
这是 获取 `cookie` 教程：https://www.yindan.me/tutorial/genshin-impact-helper.html
