### ISSUE TITLE
可不可以添加使用自己云服务器而不是使用Action

### ISSUE THREAD

**Issue by McKinleyLu** [sirodeneko/genshin-sign#31]
可不可以添加使用自己云服务器而不是使用Action

**Comment by sirodeneko** [comment]
设置好环境变量 定时运行 ```python3 ./genshin.py```  即可

**Comment by magic5al** [comment]
> 可不可以添加使用自己的云服务器而不是使用Action

请问action是有什么风险吗，我看很多地方都是说谨慎使用（虽然我已经在用了）

**Comment by sirodeneko** [comment]
> 

泄密风险？ github如果想是可以拿到的cookie的，如果我想也可以提交恶意代码获取你的cookie(如果你同步了我的提交)，你不放心可以不自动同步我的代码

**Comment by magic5al** [comment]
> 

好的谢谢说明

**Comment by Misaka-Aki** [comment]
> > 
> 
> 泄密风险？ github如果想是可以拿到的cookie的，如果我想也可以提交恶意代码获取你的cookie(如果你同步了我的提交)，你不放心可以不自动同步我的代码

不是泄密的问题，github本身不允许用action来干签到这种事，曾经出现过一大波的封仓库事件，尤其是新账户，风险更大
